// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RegistroEmpleados.Server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231027153655_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Departamentos", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfesionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DepartamentoId");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            DepartamentoId = 7,
                            Nombre = "Medicina Interna",
                            ProfesionId = 2
                        },
                        new
                        {
                            DepartamentoId = 8,
                            Nombre = "Cirugia General",
                            ProfesionId = 2
                        },
                        new
                        {
                            DepartamentoId = 9,
                            Nombre = "Pediatria",
                            ProfesionId = 2
                        },
                        new
                        {
                            DepartamentoId = 10,
                            Nombre = "Neurologia",
                            ProfesionId = 2
                        },
                        new
                        {
                            DepartamentoId = 11,
                            Nombre = "Psiquiatria",
                            ProfesionId = 2
                        },
                        new
                        {
                            DepartamentoId = 12,
                            Nombre = "Medicina de Emergencia",
                            ProfesionId = 2
                        },
                        new
                        {
                            DepartamentoId = 13,
                            Nombre = "Derecho Civil",
                            ProfesionId = 3
                        },
                        new
                        {
                            DepartamentoId = 14,
                            Nombre = "Derecho de la Salud",
                            ProfesionId = 3
                        },
                        new
                        {
                            DepartamentoId = 15,
                            Nombre = "Derecho Internacional",
                            ProfesionId = 3
                        },
                        new
                        {
                            DepartamentoId = 16,
                            Nombre = "Derecho Laboral",
                            ProfesionId = 3
                        },
                        new
                        {
                            DepartamentoId = 17,
                            Nombre = "Derecho de Familia",
                            ProfesionId = 3
                        },
                        new
                        {
                            DepartamentoId = 18,
                            Nombre = "Derecho Penal",
                            ProfesionId = 3
                        },
                        new
                        {
                            DepartamentoId = 1,
                            Nombre = "Ingenieria Civil",
                            ProfesionId = 1
                        },
                        new
                        {
                            DepartamentoId = 2,
                            Nombre = "Ingenieria Mecanica",
                            ProfesionId = 1
                        },
                        new
                        {
                            DepartamentoId = 3,
                            Nombre = "Ingenieria Quimica",
                            ProfesionId = 1
                        },
                        new
                        {
                            DepartamentoId = 4,
                            Nombre = "Ingenieria en Sistemas",
                            ProfesionId = 1
                        },
                        new
                        {
                            DepartamentoId = 5,
                            Nombre = "Ingenieria Aeroespacial",
                            ProfesionId = 1
                        },
                        new
                        {
                            DepartamentoId = 6,
                            Nombre = "Ingenieria de Software",
                            ProfesionId = 1
                        });
                });

            modelBuilder.Entity("Empleados", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AFP")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cedula")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DescuentoPrestamo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<int>("HorasExtras")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HorasTrabajadas")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Impuesto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfesionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuestoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalarioNeto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SeguroMedico")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("EmpleadoId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Profesiones", b =>
                {
                    b.Property<int>("ProfesionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("ProfesionId");

                    b.ToTable("Profesiones");

                    b.HasData(
                        new
                        {
                            ProfesionId = 1,
                            Nombre = "Ingenierio"
                        },
                        new
                        {
                            ProfesionId = 2,
                            Nombre = "Medico"
                        },
                        new
                        {
                            ProfesionId = 3,
                            Nombre = "Derecho"
                        });
                });

            modelBuilder.Entity("Puestos", b =>
                {
                    b.Property<int>("PuestoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("PuestoId");

                    b.ToTable("Puestos");

                    b.HasData(
                        new
                        {
                            PuestoId = 1,
                            DepartamentoId = 1,
                            Nombre = "Ingenierio de estructuras"
                        },
                        new
                        {
                            PuestoId = 2,
                            DepartamentoId = 1,
                            Nombre = "Ingenierio en construccion"
                        },
                        new
                        {
                            PuestoId = 3,
                            DepartamentoId = 1,
                            Nombre = "Ingenierio geotecnico"
                        },
                        new
                        {
                            PuestoId = 4,
                            DepartamentoId = 1,
                            Nombre = "Inspector de obras"
                        },
                        new
                        {
                            PuestoId = 5,
                            DepartamentoId = 1,
                            Nombre = "Ingenierio de carreteras y transporte"
                        },
                        new
                        {
                            PuestoId = 6,
                            DepartamentoId = 2,
                            Nombre = "Ingeniero de diseño mecánico"
                        },
                        new
                        {
                            PuestoId = 7,
                            DepartamentoId = 2,
                            Nombre = "Ingeniero de producción"
                        },
                        new
                        {
                            PuestoId = 8,
                            DepartamentoId = 2,
                            Nombre = "Ingeniero de mantenimiento industrial"
                        },
                        new
                        {
                            PuestoId = 9,
                            DepartamentoId = 2,
                            Nombre = "Ingeniero de automatización y control"
                        },
                        new
                        {
                            PuestoId = 10,
                            DepartamentoId = 2,
                            Nombre = "Ingeniero de energía"
                        },
                        new
                        {
                            PuestoId = 11,
                            DepartamentoId = 3,
                            Nombre = "Ingeniero de procesos químicos"
                        },
                        new
                        {
                            PuestoId = 12,
                            DepartamentoId = 3,
                            Nombre = "Ingeniero de control de calidad"
                        },
                        new
                        {
                            PuestoId = 13,
                            DepartamentoId = 3,
                            Nombre = "Ingeniero de producción de químicos"
                        },
                        new
                        {
                            PuestoId = 14,
                            DepartamentoId = 3,
                            Nombre = "Ingeniero de seguridad industrial"
                        },
                        new
                        {
                            PuestoId = 15,
                            DepartamentoId = 3,
                            Nombre = "Ingeniero ambiental"
                        },
                        new
                        {
                            PuestoId = 16,
                            DepartamentoId = 4,
                            Nombre = "Desarrollador de software"
                        },
                        new
                        {
                            PuestoId = 17,
                            DepartamentoId = 4,
                            Nombre = "Ingeniero de redes"
                        },
                        new
                        {
                            PuestoId = 18,
                            DepartamentoId = 4,
                            Nombre = "Administrador de bases de datos"
                        },
                        new
                        {
                            PuestoId = 19,
                            DepartamentoId = 4,
                            Nombre = "Analista de sistemas"
                        },
                        new
                        {
                            PuestoId = 20,
                            DepartamentoId = 4,
                            Nombre = "Ingeniero de seguridad informática"
                        },
                        new
                        {
                            PuestoId = 21,
                            DepartamentoId = 5,
                            Nombre = "Ingeniero de propulsión aeroespacial"
                        },
                        new
                        {
                            PuestoId = 22,
                            DepartamentoId = 5,
                            Nombre = "Diseñador de aeronaves"
                        },
                        new
                        {
                            PuestoId = 23,
                            DepartamentoId = 5,
                            Nombre = "Ingeniero de sistemas aviónicos"
                        },
                        new
                        {
                            PuestoId = 24,
                            DepartamentoId = 5,
                            Nombre = "Analista de estrés y fatiga"
                        },
                        new
                        {
                            PuestoId = 25,
                            DepartamentoId = 5,
                            Nombre = "Ingeniero de materiales aeroespaciales"
                        },
                        new
                        {
                            PuestoId = 26,
                            DepartamentoId = 6,
                            Nombre = "Desarrollador de aplicaciones móviles"
                        },
                        new
                        {
                            PuestoId = 27,
                            DepartamentoId = 6,
                            Nombre = "Ingeniero de QA / Tester de Software"
                        },
                        new
                        {
                            PuestoId = 28,
                            DepartamentoId = 6,
                            Nombre = "Arquitecto de software"
                        },
                        new
                        {
                            PuestoId = 29,
                            DepartamentoId = 6,
                            Nombre = "Ingeniero de DevOps"
                        },
                        new
                        {
                            PuestoId = 30,
                            DepartamentoId = 6,
                            Nombre = "Analista de seguridad de software"
                        },
                        new
                        {
                            PuestoId = 31,
                            DepartamentoId = 7,
                            Nombre = "Médico internista"
                        },
                        new
                        {
                            PuestoId = 32,
                            DepartamentoId = 7,
                            Nombre = "Cardiólogo"
                        },
                        new
                        {
                            PuestoId = 33,
                            DepartamentoId = 7,
                            Nombre = "Neumólogo"
                        },
                        new
                        {
                            PuestoId = 34,
                            DepartamentoId = 7,
                            Nombre = "Gastroenterólogo"
                        },
                        new
                        {
                            PuestoId = 35,
                            DepartamentoId = 7,
                            Nombre = "Nefrólogo"
                        },
                        new
                        {
                            PuestoId = 36,
                            DepartamentoId = 8,
                            Nombre = "Cirujano general"
                        },
                        new
                        {
                            PuestoId = 37,
                            DepartamentoId = 8,
                            Nombre = "Cirujano oncológico"
                        },
                        new
                        {
                            PuestoId = 38,
                            DepartamentoId = 8,
                            Nombre = "Cirujano de trauma"
                        },
                        new
                        {
                            PuestoId = 39,
                            DepartamentoId = 8,
                            Nombre = "Cirujano vascular"
                        },
                        new
                        {
                            PuestoId = 40,
                            DepartamentoId = 8,
                            Nombre = "Cirujano laparoscópico"
                        },
                        new
                        {
                            PuestoId = 41,
                            DepartamentoId = 9,
                            Nombre = "Pediatra general"
                        },
                        new
                        {
                            PuestoId = 42,
                            DepartamentoId = 9,
                            Nombre = "Neonatólogo"
                        },
                        new
                        {
                            PuestoId = 43,
                            DepartamentoId = 9,
                            Nombre = "Pediatra infectólogo"
                        },
                        new
                        {
                            PuestoId = 44,
                            DepartamentoId = 9,
                            Nombre = "Pediatra cardiólogo"
                        },
                        new
                        {
                            PuestoId = 45,
                            DepartamentoId = 9,
                            Nombre = "Pediatra Neurologo"
                        },
                        new
                        {
                            PuestoId = 46,
                            DepartamentoId = 10,
                            Nombre = "Neurólogo clínico"
                        },
                        new
                        {
                            PuestoId = 47,
                            DepartamentoId = 10,
                            Nombre = "Neurólogo infantil"
                        },
                        new
                        {
                            PuestoId = 48,
                            DepartamentoId = 10,
                            Nombre = "Neurólogo vascular"
                        },
                        new
                        {
                            PuestoId = 49,
                            DepartamentoId = 10,
                            Nombre = "Neurólogo epileptólogo"
                        },
                        new
                        {
                            PuestoId = 50,
                            DepartamentoId = 10,
                            Nombre = "Neurólogo neurofisiólogo"
                        },
                        new
                        {
                            PuestoId = 51,
                            DepartamentoId = 11,
                            Nombre = "Psiquiatra clínico"
                        },
                        new
                        {
                            PuestoId = 52,
                            DepartamentoId = 11,
                            Nombre = "Psiquiatra forense"
                        },
                        new
                        {
                            PuestoId = 53,
                            DepartamentoId = 11,
                            Nombre = "Psiquiatra de niños y adolescentes"
                        },
                        new
                        {
                            PuestoId = 54,
                            DepartamentoId = 11,
                            Nombre = "Psiquiatra geriátrico"
                        },
                        new
                        {
                            PuestoId = 55,
                            DepartamentoId = 11,
                            Nombre = "Psiquiatra de adicciones"
                        },
                        new
                        {
                            PuestoId = 56,
                            DepartamentoId = 12,
                            Nombre = "Médico de emergencia"
                        },
                        new
                        {
                            PuestoId = 57,
                            DepartamentoId = 12,
                            Nombre = "Médico de trauma"
                        },
                        new
                        {
                            PuestoId = 58,
                            DepartamentoId = 12,
                            Nombre = "Médico de sala de urgencias"
                        },
                        new
                        {
                            PuestoId = 59,
                            DepartamentoId = 12,
                            Nombre = "Coordinador de emergencias"
                        },
                        new
                        {
                            PuestoId = 60,
                            DepartamentoId = 12,
                            Nombre = "Médico de cuidados intensivos"
                        },
                        new
                        {
                            PuestoId = 61,
                            DepartamentoId = 13,
                            Nombre = "Notario"
                        },
                        new
                        {
                            PuestoId = 62,
                            DepartamentoId = 13,
                            Nombre = "Abogado de familia"
                        },
                        new
                        {
                            PuestoId = 63,
                            DepartamentoId = 13,
                            Nombre = "Abogado de propiedad"
                        },
                        new
                        {
                            PuestoId = 64,
                            DepartamentoId = 13,
                            Nombre = "Litigante civil"
                        },
                        new
                        {
                            PuestoId = 65,
                            DepartamentoId = 13,
                            Nombre = "Mediador civil"
                        },
                        new
                        {
                            PuestoId = 66,
                            DepartamentoId = 14,
                            Nombre = "Asesor legal de instituciones de salud"
                        },
                        new
                        {
                            PuestoId = 67,
                            DepartamentoId = 14,
                            Nombre = "Abogado de responsabilidad médica"
                        },
                        new
                        {
                            PuestoId = 68,
                            DepartamentoId = 14,
                            Nombre = "Abogado de seguros de salud"
                        },
                        new
                        {
                            PuestoId = 69,
                            DepartamentoId = 14,
                            Nombre = "Abogado de etica médica"
                        },
                        new
                        {
                            PuestoId = 70,
                            DepartamentoId = 14,
                            Nombre = "Asesor legal de laboratorios médicos"
                        },
                        new
                        {
                            PuestoId = 71,
                            DepartamentoId = 15,
                            Nombre = "Abogado de derecho internacional público"
                        },
                        new
                        {
                            PuestoId = 72,
                            DepartamentoId = 15,
                            Nombre = "Asesor legal de organizaciones internacionales"
                        },
                        new
                        {
                            PuestoId = 73,
                            DepartamentoId = 15,
                            Nombre = "Abogado de comercio internacional"
                        },
                        new
                        {
                            PuestoId = 74,
                            DepartamentoId = 15,
                            Nombre = "Abogado de derechos humanos"
                        },
                        new
                        {
                            PuestoId = 75,
                            DepartamentoId = 15,
                            Nombre = "Diplomático"
                        },
                        new
                        {
                            PuestoId = 76,
                            DepartamentoId = 16,
                            Nombre = "Abogado laboralista"
                        },
                        new
                        {
                            PuestoId = 77,
                            DepartamentoId = 16,
                            Nombre = "Asesor legal de recursos humanos"
                        },
                        new
                        {
                            PuestoId = 78,
                            DepartamentoId = 16,
                            Nombre = "Arbitro laboral"
                        },
                        new
                        {
                            PuestoId = 79,
                            DepartamentoId = 16,
                            Nombre = "Mediador laboral"
                        },
                        new
                        {
                            PuestoId = 80,
                            DepartamentoId = 16,
                            Nombre = "Abogado de seguridad laboral"
                        },
                        new
                        {
                            PuestoId = 81,
                            DepartamentoId = 17,
                            Nombre = "Abogado de divorcio"
                        },
                        new
                        {
                            PuestoId = 82,
                            DepartamentoId = 17,
                            Nombre = "Abogado de custodia"
                        },
                        new
                        {
                            PuestoId = 83,
                            DepartamentoId = 17,
                            Nombre = "Mediador familiar"
                        },
                        new
                        {
                            PuestoId = 84,
                            DepartamentoId = 17,
                            Nombre = "Abogado de adopciones"
                        },
                        new
                        {
                            PuestoId = 85,
                            DepartamentoId = 17,
                            Nombre = "Abogado de violencia doméstica"
                        },
                        new
                        {
                            PuestoId = 86,
                            DepartamentoId = 18,
                            Nombre = "Fiscal"
                        },
                        new
                        {
                            PuestoId = 87,
                            DepartamentoId = 18,
                            Nombre = "Abogado defensor penal"
                        },
                        new
                        {
                            PuestoId = 88,
                            DepartamentoId = 18,
                            Nombre = "Juez de lo penal"
                        },
                        new
                        {
                            PuestoId = 89,
                            DepartamentoId = 18,
                            Nombre = "Investigador criminal"
                        },
                        new
                        {
                            PuestoId = 90,
                            DepartamentoId = 18,
                            Nombre = "Abogado de libertad condicional"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
